### ISSUE TITLE
func-tests don't run (on linux?)

### ISSUE THREAD

**Issue by grandchild** [azeem/webvs#46]
I'm getting the following output when I run `npm run func-test`:

```
CHROME_BIN=chromium npm run func-test
```
```
> webvs@3.0.0 func-test /home/jakob/dev/avs/webvs
> karma start

Hash: 6da5611acdaf99197223
Version: webpack 3.11.0
Time: 55ms
webpack: Compiled successfully.
webpack: Compiling...
26 06 2018 01:17:27.577:WARN [karma]: No captured browser, open http://localhost:9876/
26 06 2018 01:17:27.581:INFO [karma]: Front-end scripts not present. Compiling...
Hash: a2b93713f0b8548e6729
Version: webpack 3.11.0
Time: 6000ms
                 Asset    Size  Chunks                    Chunk Names
test/func/testIndex.ts  813 kB       0  [emitted]  [big]  test/func/testIndex.ts
 [145] ./test/func/testIndex.ts 101 bytes {0} [built]
 [146] ./test/func \.test$ 555 bytes {0} [built]
 [147] ./test/func/Main.test.ts 771 bytes {0} [optional] [built]
 [327] ./test/func/render/ClearScreen.test.ts 1.43 kB {0} [optional] [built]
 [329] ./test/func/render/SuperScope.test.ts 3 kB {0} [optional] [built]
 [330] ./test/func/render/Texer.test.ts 1.59 kB {0} [optional] [built]
 [331] ./test/func/trans/ChannelShift.test.ts 1.25 kB {0} [optional] [built]
 [332] ./test/func/trans/ColorClip.test.ts 1.37 kB {0} [optional] [built]
 [334] ./test/func/trans/Convolution.test.ts 1.67 kB {0} [optional] [built]
 [335] ./test/func/trans/DynamicMovement.test.ts 3 kB {0} [optional] [built]
 [336] ./test/func/trans/FadeOut.test.ts 1.38 kB {0} [optional] [built]
 [337] ./test/func/trans/Invert.test.ts 343 bytes {0} [optional] [built]
 [338] ./test/func/trans/Mirror.test.ts 4.63 kB {0} [optional] [built]
 [348] ./test/func/trans/Mosaic.test.ts 1.43 kB {0} [optional] [built]
 [349] ./test/func/trans/UniqueTone.test.ts 1.74 kB {0} [optional] [built]
    + 335 hidden modules

ERROR in ./node_modules/@visbot/webvsc/node.js
Module not found: Error: Can't resolve 'fs' in '/home/jakob/dev/avs/webvs/node_modules/@visbot/webvsc'
 @ ./node_modules/@visbot/webvsc/node.js 43:11-24
 @ ./src/Main.ts
 @ ./test/func/funcTestUtils.ts
 @ ./test/func/Main.test.ts
 @ ./test/func \.test$
 @ ./test/func/testIndex.ts

ERROR in ./node_modules/@visbot/webvsc/lib/util-node.js
Module not found: Error: Can't resolve 'fs' in '/home/jakob/dev/avs/webvs/node_modules/@visbot/webvsc/lib'
 @ ./node_modules/@visbot/webvsc/lib/util-node.js 4:11-24
 @ ./node_modules/@visbot/webvsc/node.js
 @ ./src/Main.ts
 @ ./test/func/funcTestUtils.ts
 @ ./test/func/Main.test.ts
 @ ./test/func \.test$
 @ ./test/func/testIndex.ts
webpack: Failed to compile.
26 06 2018 01:17:28.366:INFO [karma]: Karma v2.0.0 server started at http://0.0.0.0:9876/
26 06 2018 01:17:28.367:INFO [launcher]: Launching browser Chrome with unlimited concurrency
26 06 2018 01:17:28.372:INFO [launcher]: Starting browser Chrome
26 06 2018 01:17:29.126:INFO [Chrome 67.0.3396 (Linux 0.0.0)]: Connected on socket SnS1YWym_ZVLsPsSAAAA with id 1971824

START:
Chrome 67.0.3396 (Linux 0.0.0) ERROR
  {
    "message": "Uncaught Error: Cannot find module \"fs\"
    at test/func/testIndex.ts:13405:145
    
    Error: Cannot find module \"fs\"
        at webpackMissingModule (test/func/testIndex.ts:13405:76)
        at Object.defineProperty.value (test/func/testIndex.ts:13405:155)
        at __webpack_require__ (test/func/testIndex.ts:20:30)
        at Object.<anonymous> (test/func/testIndex.ts:12417:12)
        at __webpack_require__ (test/func/testIndex.ts:20:30)
        at Object.<anonymous> (test/func/testIndex.ts:11870:16)
        at __webpack_require__ (test/func/testIndex.ts:20:30)
        at Object.<anonymous> (test/func/testIndex.ts:1067:14)
        at __webpack_require__ (test/func/testIndex.ts:20:30)
        at Object.<anonymous> (test/func/testIndex.ts:8143:23)",
    
    
    "str": "Uncaught Error: Cannot find module \"fs\"
    at test/func/testIndex.ts:13405:145
    
    Error: Cannot find module \"fs\"
        at webpackMissingModule (test/func/testIndex.ts:13405:76)
        at Object.defineProperty.value (test/func/testIndex.ts:13405:155)
        at __webpack_require__ (test/func/testIndex.ts:20:30)
        at Object.<anonymous> (test/func/testIndex.ts:12417:12)
        at __webpack_require__ (test/func/testIndex.ts:20:30)
        at Object.<anonymous> (test/func/testIndex.ts:11870:16)
        at __webpack_require__ (test/func/testIndex.ts:20:30)
        at Object.<anonymous> (test/func/testIndex.ts:1067:14)
        at __webpack_require__ (test/func/testIndex.ts:20:30)
        at Object.<anonymous> (test/func/testIndex.ts:8143:23)"

  }

Finished in 0.132 secs / 0 secs @ 01:17:29 GMT+0200 (Central European Summer Time)

SUMMARY:
✔ 0 tests completed
```
(Formatted a bit for legibility)

**Comment by grandchild** [comment]
nevermind...
